# Generated by Django 4.2.6 on 2023-10-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_alter_book_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=5)),
            ],
        ),
    ]
